pro/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    
]

users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path
from . import views
from .views import export_to_excel
app_name = 'users'

urlpatterns = [
    path('index/', views.index, name='index'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path('prof/', views.profile, name='profile'),
    path('attendance_by_teacher/', views.attendance_by_teacher, name='teacher'),
    path('create_att/<int:ls_id>/<int:st_id>/', views.create_attendance_teacher, name='create_att'),
    path('remove_att/<int:ls_id>/<int:st_id>/', views.remove_attendance_teacher, name='remove_att'),
    path('create_stud/<int:ls_id>/<int:st_id>/', views.create_attendace_stud, name='create_att_stud'),
    path('remove_stud/<int:ls_id>/<int:st_id>/', views.remove_attendace_stud, name='remove_att_stud'),
    path('attendance_by_headman/', views.attendance_by_headman, name='headman'),
    path('rdir_to_login', views.rdir_to_login, name = 'rdir'),
    path('remove_att_hd/<int:ls_id>/<int:st_id>/', views.remove_attendance_headman, name='remove_att_hd'),
    path('create_att_hd/<int:ls_id>/<int:st_id>/', views.create_attendance_headman, name='create_att_hd'),
    path('lessons/', views.lessons, name='lessons'),
    path('lesson_detail/<int:id>', views.lesson_detail, name='lesson_detail'),
    path('export/<int:id>/', export_to_excel, name='export_to_excel'),
    path('start_timer/<int:id>/', views.att_timer, name='timer')

    
]  

templates/index.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Авторизация</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  
  <body class="bg-primary-subtle" style="background: linear-gradient( white, #4c76e3); height: 100vh;">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <img src="{% static 'img/logo.svg' %}" alt="..." width="200px" height="100px">
    {% if user.is_authenticated %}
    вы вошли
    {% else %}
    <div class="container text-center ">
        <div class="row justify-content-md-center gy-4 p-5">
            <div class="col-md-auto fs-3">
        <form action="{% url 'users:login' %}" method="post">
            <div class="mb-3">
              <label for="exampleInputEmail1" class="form-label">Имя пользователя</label>
              <input type="text" class="form-control" id="exampleInputText1" aria-describedby="emailHelp">
              <div id="emailHelp" class="form-text"></div>
            </div>
            <div class="mb-3">
              <label for="exampleInputPassword1" class="form-label">Пароль</label>
              <input type="password" class="form-control" id="exampleInputPassword1">
            </div>
            
            <button type="submit" class="btn btn-primary">Авторизоваться</button>
            {% csrf_token %}
          </form>
        </div> </div>
    </div>
    {% endif %}
  </body>
</html>