pro/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    
]

users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path
from . import views
from .views import export_to_excel
app_name = 'users'

urlpatterns = [
    path('index/', views.index, name='index'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path('prof/', views.profile, name='profile'),
    path('attendance_by_teacher/', views.attendance_by_teacher, name='teacher'),
    path('create_att/<int:ls_id>/<int:st_id>/', views.create_attendance_teacher, name='create_att'),
    path('remove_att/<int:ls_id>/<int:st_id>/', views.remove_attendance_teacher, name='remove_att'),
    path('create_stud/<int:ls_id>/<int:st_id>/', views.create_attendace_stud, name='create_att_stud'),
    path('remove_stud/<int:ls_id>/<int:st_id>/', views.remove_attendace_stud, name='remove_att_stud'),
    path('attendance_by_headman/', views.attendance_by_headman, name='headman'),
    path('rdir_to_login', views.rdir_to_login, name = 'rdir'),
    path('remove_att_hd/<int:ls_id>/<int:st_id>/', views.remove_attendance_headman, name='remove_att_hd'),
    path('create_att_hd/<int:ls_id>/<int:st_id>/', views.create_attendance_headman, name='create_att_hd'),
    path('lessons/', views.lessons, name='lessons'),
    path('lesson_detail/<int:id>', views.lesson_detail, name='lesson_detail'),
    path('export/<int:id>/', export_to_excel, name='export_to_excel'),
    path('start_timer/<int:id>/', views.att_timer, name='timer')

    
]  

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from datetime import datetime, timedelta

class StudyGroup(models.Model): 
    group_name = models.CharField(max_length=150) 
    course_number = models.IntegerField()
    
    def __str__(self):
        return self.group_name
    
    class Meta:
        
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'


class User(AbstractUser):
    email = models.EmailField(
        max_length=254,
        unique=True,
        verbose_name='Адрес электронной почты'
    )
    username = models.CharField(
        max_length=150,
        unique=True,
        verbose_name='Имя пользователя'
    )
    first_name = models.CharField(
        max_length=150,
        verbose_name='Имя'
    )
    last_name = models.CharField(
        max_length=150,
        verbose_name='Фамилия'
    )
    second_name = models.CharField(
        max_length=150,
        verbose_name='Отчество'
    )
    group = models.ForeignKey(StudyGroup, 
                              on_delete=models.CASCADE, 
                              related_name='group_students', null=True, blank=True) 
    
    is_student = models.BooleanField(default=False)
    is_teacher = models.BooleanField(default=False)
    is_headman = models.BooleanField(default=False)

    #USERNAME_FIELD = 'email'
    #REQUIRED_FIELDS = ('username', 'first_name', 'last_name', 'is_student', 'is_teacher', 'is_headman')

    class Meta:
        ordering = ('username',)
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.username


 
class AttendanceCheck(models.Model): 
    pass 
 
class Discipline(models.Model): 
    title = models.CharField(max_length=150, verbose_name='Дисциплина') 
 
    def __str__(self): 
        return self.title
    
    class Meta:
        
        verbose_name = 'Дисциплина'
        verbose_name_plural = 'Дисциплины'
 
class Lesson(models.Model): 
    start_time = models.DateTimeField() 
    end_time = models.DateTimeField()
    place = models.CharField(max_length=50, verbose_name='Аудитория', default='3 корпус 325 ауд.')
    lecturer = models.ForeignKey(User,
                                 on_delete=models.CASCADE,
                                 related_name='lessons',
                                 verbose_name='Лектор')
    discipline = models.ForeignKey( 
        Discipline, 
        on_delete=models.CASCADE, 
    ) 
    group = models.ForeignKey(StudyGroup, 
                              on_delete=models.SET_NULL, 
                              related_name='group_lessons', null=True, blank=True) 
     
    def __str__(self): 
        return self.discipline.title 
    
    class Meta:
        
        verbose_name = 'Пара'
        verbose_name_plural = 'Пары'

class AttendTimer(models.Model):
    start_time = models.DateTimeField(auto_now_add=True)
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE, related_name='timer', null=True, blank=True)
    def __str__(self): 
        return 'timer'
 
class Attendance(models.Model): 
    lesson = models.ForeignKey( 
        Lesson, 
        on_delete=models.CASCADE, 
        related_name='lesson', 
    ) 
    student = models.ForeignKey( 
        User, 
        on_delete=models.CASCADE, 
        related_name='student', 
    ) 
    isPresent = models.BooleanField(default=False)

    class Meta:
        
        verbose_name = 'Посещение'
        verbose_name_plural = 'Посещения'

users/views.py
from django.shortcuts import get_object_or_404, redirect, render
import datetime
from users.models import User, Attendance, Lesson
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from openpyxl import Workbook
from users.models import Attendance, AttendTimer

def index(request):
    hello = 'hello'
    return render(request, 'index.html', {'hello': hello})

def profile(request):
    user = request.user
    dt_now = datetime.datetime.now()
    lessons = user.lessons.all()
    actual_lesson = ''
    end_t = ''
    st_lesson = ''
    end_t_st = ''
    hd_lesson = ''
    end_t_hd = ''
    att = False
    can_attend = False
    if request.user.is_headman:
        
        group = user.group
        hd_lessons = group.group_lessons.all()
        for lesson in hd_lessons:
            if (lesson.start_time.timestamp() < dt_now.timestamp()) and (lesson.end_time.timestamp() > dt_now.timestamp()):
                hd_lesson = lesson
        if hd_lesson:
            end_t_hd = hd_lesson.end_time.strftime('%H:%M')
        

    if request.user.is_student:
        
        group = user.group
        st_lessons = group.group_lessons.all()
        for lesson in st_lessons:
            if (lesson.start_time.timestamp() < dt_now.timestamp()) and (lesson.end_time.timestamp() > dt_now.timestamp()):
                st_lesson = lesson
        if st_lesson:
            end_t_st = st_lesson.end_time.strftime('%H:%M')
        
        att = Attendance.objects.filter(lesson=st_lesson, student=request.user)
        timer = False
        timers = st_lesson.timer.all()
        can_attend = False
        for time in timers:
            if (time.start_time.timestamp() < dt_now.timestamp()) and ((time.start_time + datetime.timedelta(minutes=15)).timestamp() > dt_now.timestamp()):
                can_attend = True
            else:
                can_attend = False


    for lesson in lessons:
        if (lesson.start_time.timestamp() < dt_now.timestamp()) and (lesson.end_time.timestamp() > dt_now.timestamp()):
            actual_lesson = lesson
    if actual_lesson:
        end_t = actual_lesson.end_time.strftime('%H:%M')
    
        
    return render(request, 'users/profile.html', {'user': user,
                                                  'dt_now': dt_now,
                                                  'actual_lesson': actual_lesson,
                                                  'end_t': end_t,
                                                  'st_lesson': st_lesson,
                                                  'end_t_st': end_t_st,
                                                  'att':att,
                                                  'end_t_hd': end_t_hd,
                                                  'hd_lesson': hd_lesson,
                                                  'can_attend': can_attend})
@login_required
def attendance_by_teacher(request):
    user = request.user
    dt_now = datetime.datetime.now()
    lessons = user.lessons.all()
    actual_lesson = False
    for lesson in lessons:
        if (lesson.start_time.timestamp() < dt_now.timestamp()) and (lesson.end_time.timestamp() > dt_now.timestamp()):
            actual_lesson = lesson
    if actual_lesson:
        end_t = actual_lesson.end_time.strftime('%H:%M')
        students = actual_lesson.group.group_students.all()
    attendance = False;
    attendances = {}
    for student in students:
        attendances[student] = Attendance.objects.filter(lesson=actual_lesson, student=student)

    
    return render(request, 'users/attendance_by_teacher.html', {'actual_lesson':actual_lesson,
                                                                'end_t': end_t,
                                                                'students': students,
                                                                'attendances': attendances})

@login_required
def attendance_by_headman(request):
    user = request.user
    dt_now = datetime.datetime.now()
    group = user.group
    hd_lessons = group.group_lessons.all()
    actual_lesson = False
    for lesson in hd_lessons:
        if (lesson.start_time.timestamp() < dt_now.timestamp()) and (lesson.end_time.timestamp() > dt_now.timestamp()):
            actual_lesson = lesson
    if actual_lesson:
        end_t = actual_lesson.end_time.strftime('%H:%M')
        students = actual_lesson.group.group_students.all()
    attendances = {}
    for student in students:
        attendances[student] = Attendance.objects.filter(lesson=actual_lesson, student=student)
    return render(request, 'users/attendance_by_headman.html', {'actual_lesson':actual_lesson,
                                                                'end_t': end_t,
                                                                'students': students,
                                                                'attendances': attendances})

def create_attendance_teacher(request, ls_id, st_id):
    lesson = Lesson.objects.get(id = ls_id)
    user = User.objects.get(id = st_id)
    Attendance.objects.create(lesson = lesson, student = user)

    return redirect('users:teacher')

def remove_attendance_teacher(request, ls_id, st_id):
    lesson = Lesson.objects.get(id = ls_id)
    user = User.objects.get(id = st_id)
    
    object = Attendance.objects.filter(lesson = lesson, student = user)
    if object.exists():
        object.delete()

    return redirect('users:teacher')

def create_attendace_stud(request, ls_id, st_id):
    lesson = Lesson.objects.get(id = ls_id)
    user = User.objects.get(id = st_id)

    Attendance.objects.create(lesson = lesson, student = user)
    
    return redirect('users:profile')

def remove_attendace_stud(request, ls_id, st_id):
    lesson = Lesson.objects.get(id = ls_id)
    user = User.objects.get(id = st_id)

    object = Attendance.objects.filter(lesson = lesson, student = user)
    if object.exists():
        object.delete()
    
    return redirect('users:profile')

def rdir_to_login(request):
    return redirect('users:login')



def create_attendance_headman(request, ls_id, st_id):
    lesson = Lesson.objects.get(id = ls_id)
    user = User.objects.get(id = st_id)
    Attendance.objects.create(lesson = lesson, student = user)

    return redirect('users:headman')

def remove_attendance_headman(request, ls_id, st_id):
    lesson = Lesson.objects.get(id = ls_id)
    user = User.objects.get(id = st_id)
    
    object = Attendance.objects.filter(lesson = lesson, student = user)
    if object.exists():
        object.delete()

    return redirect('users:headman')


def lessons(request):
    lessons = request.user.lessons.all()
    return render(request, 'users/lessons.html', {'lessons': lessons})


def lesson_detail(request, id):
    lesson = get_object_or_404(Lesson, id=id)
    group = lesson.group
    students = group.group_students.all()
    attendances = {}
    for student in students:
        attendances[student] = Attendance.objects.filter(lesson=lesson, student=student)
    

    
    return render(request, 'users/lesson_detail.html', {'lesson':lesson, 'students':students, 'attendances': attendances})


def export_to_excel(request, id):
    response = HttpResponse(content_type='application/ms-excel')
    response['Content-Disposition'] = 'attachment; filename="products.xlsx"'
    lesson = Lesson.objects.get(id=id)

    wb = Workbook()
    ws = wb.active
    ws.title = 'title'

    # Add headers
    headers = ["Студент", "Был не был"]
    ws.append(headers)

    lesson = get_object_or_404(Lesson, id=id)
    group = lesson.group
    students = group.group_students.all()
    attendances = {}
    for student in students:
        attendances[student] = Attendance.objects.filter(lesson=lesson, student=student)
    for st, att in attendances:
        ws.append([st, att])

    # Save the workbook to the HttpResponse
    wb.save(response)
    return response

def att_timer(request,id):
    lesson = get_object_or_404(Lesson, id=id)
    AttendTimer.objects.create(lesson=lesson)
    return redirect('users:profile')

templates/users/attendance_by_headman.html
<!doctype html>
<html lang="en">
    {% load static %}
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body style="background: #f6f4ef; height: 100vh; ">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <div style="background-color: #18202b;" class="text-end p-2">
        <a href="{% url 'users:logout' %}">
            <img src="{% static 'img/exit.png' %}" alt="..." width="12x" height="12px">
          </a>
                <!-- Прописать путь -->
            
            
            
    </div>
    <!-- Прописать путь -->
    <img src="{% static 'img/logo.svg' %}" alt="..." width="200px" height="100px">
    <div style="background-color: #0b2d50;" class="p-3">
        <span class="fw-bold text-white">Вы авторизовались как: </span>
        <span class="fw-bold text-white">{{user.last_name}} {{user.first_name}} {{user.second_name}} </span>
    </div>
    <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
                <div class="card-header">
                  Текущая пара: {{ actual_lesson }}
                </div>
                <div class="card-body">

    <table class="table">

        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Студент</th>
            <th scope="col">Пара</th>
            <th scope="col">Был не был</th>
          </tr>
        </thead>
        <tbody>
            {% for student, attendance in attendances.items %}
            
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{student.first_name}} {{student.last_name}}</td>
            <td>{{actual_lesson.start_time}} - {{end_t}}</td>
            <td>{% if attendance %}<a class="btn btn-warning btn-sm" href="{% url 'users:remove_att' actual_lesson.id student.id %}" role="button">Отменить отметку</a>{% else %}
                <a class="btn btn-primary btn-sm" href="{% url 'users:create_att' actual_lesson.id student.id %}" role="button">Отметить</a> {% endif %}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      <a href="{% url 'users:profile' %}" class="btn btn-primary">Назад</a>
    </div></div></div></div></div>

templates/users/attendance_by_teacher.html
{% load static %}<!doctype html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body style="background: #f6f4ef; height: 100vh; ">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <div style="background-color: #18202b;" class="text-end p-2">
      <a href="{% url 'users:logout' %}">
        <button style="color: white;" type="button" class="btn fw-bold ">
          <!-- Прописать путь -->
          <img src="{% static 'img/exit.png' %}" alt="..." width="12x" height="12px">
          Выйти
      </button>
      </a>
            
    </div>
    <!-- Прописать путь -->
    <img src="{% static 'img/logo.svg' %}" alt="..." width="200px" height="100px">
    <div style="background-color: #0b2d50;" class="p-3">
        <span class="fw-bold text-white">Вы авторизовались как: </span>
        <span class="fw-bold text-white">{{user.last_name}} {{user.first_name}} {{user.second_name}} </span>
    </div>
    <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
                <div class="card-header">
                  Текущая пара: {{ actual_lesson }}
                </div>
                <div class="card-body">

    <table class="table">

        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Студент</th>
            <th scope="col">Пара</th>
            <th scope="col">Был не был</th>
          </tr>
        </thead>
        <tbody>
            {% for student, attendance in attendances.items %}
            
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{student.first_name}} {{student.last_name}}</td>
            <td>{{actual_lesson.start_time}} - {{end_t}}</td>
            <td>{% if attendance %}<a class="btn btn-warning btn-sm" href="{% url 'users:remove_att' actual_lesson.id student.id %}" role="button">Отменить отметку</a>{% else %}
                <a class="btn btn-primary btn-sm" href="{% url 'users:create_att' actual_lesson.id student.id %}" role="button">Отметить</a> {% endif %}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      <a href="{% url 'users:profile' %}" class="btn btn-primary">Назад</a>
    </div></div></div></div></div>
   
   
    

templates/users/lesson_detail.html
{% load static %}<!doctype html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body style="background: #f6f4ef; height: 100vh; ">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <div style="background-color: #18202b;" class="text-end p-2">
        <a href="{% url 'users:logout' %}">
            <button style="color: white;" type="button" class="btn fw-bold ">
              <!-- Прописать путь -->
              <img src="{% static 'img/exit.png' %}" alt="..." width="12x" height="12px">
              Выйти
          </button>
          </a>
            
    </div>
    <!-- Прописать путь -->
    <img src="{% static 'img/logo.svg' %}" alt="..." width="200px" height="100px">
    <div style="background-color: #0b2d50;" class="p-3">
        <span class="fw-bold text-white">Вы авторизовались как: </span>
        <span class="fw-bold text-white">{{user.last_name}} {{user.first_name}} {{user.second_name}} </span>
    </div>
    <div class="container py-5">
        <div class="row justify-content-center">
            
          <div class="col-md-8 p-5">
            
            <div class="card">
                <div class="card-header">
                  {{ lesson }}
                </div>
                <div class="card-body">
                    <table class="table">
                        <thead>
                          <tr>
                            <th scope="col">#</th>
                            <th scope="col">Студент</th>
                            <th scope="col">Пара</th>
                            <th scope="col">Был не был</th>
                          </tr>
                        </thead>
                        <tbody>
                            {% for student, at in attendances.items %}
                            
                          <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{student.first_name}} {{student.last_name}}</td>
                            <td>{{lesson.start_time}} </td>
                            <td>{% if at %} + {% else %} - {% endif %}</td>
                          </tr>
                          {% endfor %}
                          
                        </tbody>
                        <a href="{% url 'users:lessons' %}" class="btn btn-primary">Назад</a>
                        {#<a href="{% url 'users:export_to_excel' lesson.id %}" class="btn btn-primary">Эксель</a>#}
                </div>
              </div>

            
              
    </div>
</div></div></div></div>

templates/users/logged_out.html
<!doctype html>
{% load static %}
{% load user_filters %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Авторизация</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  
  <body class="bg-primary-subtle" style="background: linear-gradient( white, #4c76e3); height: 100vh;">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <img src="{% static 'img/logo.svg' %}" alt="..." width="200px" height="100px">
    {% if user.is_authenticated %}
    
    {% else %}
    <div class="container text-center ">
        <div class="row justify-content-md-center gy-4 p-5">
            <div class="col-md-3 ">
    <a href="{% url 'users:rdir' %}" class="btn btn-primary">На страницу авторизации</a>
            </div></div></div>
    {% endif %}
  </body>
</html>

templates/users/profile.html
{% load static %}<!doctype html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Attendace</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body style="background: #f6f4ef; height: 100vh; ">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <div style="background-color: #18202b;" class="text-end p-2">
      <a href="{% url 'users:logout' %}">
        <button style="color: white;" type="button" class="btn fw-bold ">
          <!-- Прописать путь -->
          <img src="{% static 'img/exit.png' %}" alt="..." width="12x" height="12px">
          Выйти
      </button>
      </a>
            
    </div>
    <!-- Прописать путь -->
    <img src="{% static 'img/logo.svg' %}" alt="..." width="200px" height="100px">
    <div style="background-color: #0b2d50;" class="p-3">
        <span class="fw-bold text-white">Вы авторизовались как: </span>
        <span class="fw-bold text-white">{{user.last_name}} {{user.first_name}} {{user.second_name}} </span>
    </div>
    {% if user.is_teacher %}
    {% if actual_lesson %}
    <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
    <div class="card">
        <div class="card-header">
          Текущая пара 
        </div>
        <div class="card-body">
          <h5 class="card-title">{{ actual_lesson }}</h5>
          <p class="card-text">{{actual_lesson.start_time}} - {{end_t}} <br> {{ actual_lesson.place }} </p>
          <a href="{% url 'users:teacher' %}" class="btn btn-primary">Отметить студентов</a> 
          <a href="{% url 'users:timer' actual_lesson.id %}" class="btn btn-primary">    Запустить таймер           
</a>

          
          <a href="{% url 'users:lessons' %}" class="btn btn-primary">К списку пар</a>
        </div>
      </div>
      </div></div></div>
    </div>
    
    {% else %}
    <div class="container py-5">
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
    В данный момент пар нет, приходите позже! <a class="btn btn-primary btn-sm " href="{% url 'users:profile'%}" role="button">F5</a>
    {% endif %}
    {% endif %}
    {% if user.is_student %}
    {% if st_lesson %}
    <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
    <div class="card">
        <div class="card-header">
          Текущая пара 
        </div>
        <div class="card-body">
          <h5 class="card-title">{{ st_lesson }}</h5>
          <p class="card-text">{{st_lesson.start_time}} - {{end_t_st}} <br> {{ st_lesson.place }} </p>

          {% if can_attend %}
          {% if att %} <a href="{% url 'users:remove_att_stud' st_lesson.id user.id %}" class="btn btn-warning">Удалить отметку</a>{% else %}<a href="{% url 'users:create_att_stud' st_lesson.id user.id %}" class="btn btn-primary">Отметиться</a>{%endif%}
          {% else %}
          Перекличка еще не началась
          {% endif %}
        </div>

      </div>
      </div></div></div>
    </div>
    
    {% else %}
    <div class="container py-5">
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
    В данный момент пар нет, приходите позже! <a class="btn btn-primary btn-sm " href="{% url 'users:profile'%}" role="button">F5</a>
    {% endif %}
    {% endif %}

    {% if user.is_headman %}
    {% if hd_lesson %}
    <div class="container py-5">
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Текущая пара 
      </div>
      <div class="card-body">
        <h5 class="card-title">{{ hd_lesson }}</h5>
        <p class="card-text">{{ hd_lesson.start_time }} - {{end_t_hd}} <br> {{ hd_lesson.place }} </p>
        <a href="{% url 'users:headman' %}" class="btn btn-primary">Отметить студентов</a>
      </div>
    </div>
    </div></div></div>
  </div>
  {% else %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
  В данный момент пар нет, приходите позже! <a class="btn btn-primary btn-sm " href="{% url 'users:profile'%}" role="button">F5</a>
  {% endif %}
  
    
    {% endif %}
</body>
</html>